---
plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

env:
  node: true

parser: "babel-eslint"

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

rules:
  no-console: 0
  import/extensions: 0
