name: hexlet-check
on:
  - push

env:
  PROJECT_IMAGE: hexletprojects/js_l3_page_loader3_project

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hexlet project check
        uses: hexlet/project-action@release
        with:
          project_image: ${{ env.PROJECT_IMAGE }}
